# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.jobset_v1alpha2_worker_status import JobsetV1alpha2WorkerStatus

class TestJobsetV1alpha2WorkerStatus(unittest.TestCase):
    """JobsetV1alpha2WorkerStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobsetV1alpha2WorkerStatus:
        """Test JobsetV1alpha2WorkerStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobsetV1alpha2WorkerStatus`
        """
        model = JobsetV1alpha2WorkerStatus()
        if include_optional:
            return JobsetV1alpha2WorkerStatus(
                barrier_started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return JobsetV1alpha2WorkerStatus(
                barrier_started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testJobsetV1alpha2WorkerStatus(self):
        """Test JobsetV1alpha2WorkerStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
