apiVersion: batch/v1
kind: Job
metadata:
  name: simple-test
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: worker
        image: busybox
        restartPolicy: Always
        command: ['/bin/sh', '-c']
        args:
        - |
          echo "$(date '+%Y/%m/%d %H:%M:%S') Start"
          while true; do
            echo "$(date '+%Y/%m/%d %H:%M:%S') I'm alive"
            sleep 1
          done
          echo "$(date '+%Y/%m/%d %H:%M:%S') End"
      containers:
      - name: agent
        image: <CHANGE ME>
        securityContext:
          privileged: true
        volumeMounts:
        - name: cri-socket
          mountPath: /run/containerd/containerd.sock
      volumes:
      - name: cri-socket
        hostPath:
          path: /run/containerd/containerd.sock
          type: Socket
