apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: simple-jobset-multiple
spec:
  failurePolicy:
    restartStrategy: RestartInPlace
    restartTimeoutSeconds: 60
  replicatedJobs:
  - name: workers
    replicas: 2
    template:
      spec:
        completions: 2
        parallelism: 2
        template:
          spec:
            containers:
            - name: worker
              image: busybox
              command: ['/bin/sh', '-c']
              args:
              - |
                echo "$(date '+%Y/%m/%d %H:%M:%S') Start"

                sleep infinity

                echo "$(date '+%Y/%m/%d %H:%M:%S') End"
