apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
spec:
  selector:
    matchLabels:
      app: valkey
  replicas: 1
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
      - name: valkey
        image: valkey/valkey:8.1.0-alpine3.21
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
spec:
  type: ClusterIP
  selector:
    app: valkey
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
