# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from jobset.models.jobset_v1alpha2_worker_status import JobsetV1alpha2WorkerStatus
from typing import Optional, Set
from typing_extensions import Self

class JobsetV1alpha2RestartGroupStatus(BaseModel):
    """
    RestartGroupStatus defines the observed state of RestartGroup
    """ # noqa: E501
    worker_statuses: Optional[Dict[str, JobsetV1alpha2WorkerStatus]] = Field(default=None, alias="workerStatuses")
    __properties: ClassVar[List[str]] = ["workerStatuses"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobsetV1alpha2RestartGroupStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in worker_statuses (dict)
        _field_dict = {}
        if self.worker_statuses:
            for _key_worker_statuses in self.worker_statuses:
                if self.worker_statuses[_key_worker_statuses]:
                    _field_dict[_key_worker_statuses] = self.worker_statuses[_key_worker_statuses].to_dict()
            _dict['workerStatuses'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobsetV1alpha2RestartGroupStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workerStatuses": dict(
                (_k, JobsetV1alpha2WorkerStatus.from_dict(_v))
                for _k, _v in obj["workerStatuses"].items()
            )
            if obj.get("workerStatuses") is not None
            else None
        })
        return _obj


